In [24]:
import pandas as pd
import numpy as np

In [26]:
df = pd.read_csv("starbucks-menu-nutrition-drinks.csv")

In [29]:
df.replace(to_replace="-",value=np.nan,inplace=True)
df.isnull().sum()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 7 columns):
Unnamed: 0    177 non-null object
Calories      92 non-null object
Fat (g)       92 non-null object
Carb. (g)     92 non-null object
Fiber (g)     92 non-null object
Protein       92 non-null object
Sodium        92 non-null object
dtypes: object(7)
memory usage: 9.8+ KB

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 7 columns):
Unnamed: 0    177 non-null object
Calories      92 non-null object
Fat (g)       92 non-null object
Carb. (g)     92 non-null object
Fiber (g)     92 non-null object
Protein       92 non-null object
Sodium        92 non-null object
dtypes: object(7)
memory usage: 9.8+ KB

In [31]:
df.describe()

,Unnamed: 0,Calories,Fat (g),Carb. (g),Fiber (g),Protein,Sodium
count,177,92,92,92,92,92,92
unique,154,29,14,33,7,16,24
top,Tazo® Bottled Brambleberry,140,0,35,0,0,10
freq,2,13,54,11,80,45,28

In [37]:
df = pd.read_csv("starbucks_drinkMenu_expanded.csv")
df.head()

,Beverage_category,Beverage,Beverage_prep,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg)
0,Coffee,Brewed Coffee,Short,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0%,0%,0%,0%,175
1,Coffee,Brewed Coffee,Tall,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0%,0%,0%,0%,260
2,Coffee,Brewed Coffee,Grande,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,0%,0%,330
3,Coffee,Brewed Coffee,Venti,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,2%,0%,410
4,Classic Espresso Drinks,Caffè Latte,Short Nonfat Milk,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10%,0%,20%,0%,75

In [36]:
print(df.isnull().sum())
df.describe()

Beverage_category            0
Beverage                     0
Beverage_prep                0
Calories                     0
 Total Fat (g)               0
Trans Fat (g)                0
Saturated Fat (g)            0
 Sodium (mg)                 0
 Total Carbohydrates (g)     0
Cholesterol (mg)             0
 Dietary Fibre (g)           0
 Sugars (g)                  0
 Protein (g)                 0
Vitamin A (% DV)             0
Vitamin C (% DV)             0
 Calcium (% DV)              0
Iron (% DV)                  0
Caffeine (mg)                1
dtype: int64

,Calories,Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g)
count,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000
mean,193.871901,1.307025,0.037603,6.363636,128.884298,35.991736,0.805785,32.962810,6.978512
std,102.863303,1.640259,0.071377,8.630257,82.303223,20.795186,1.445944,19.730199,4.871659
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,120.000000,0.100000,0.000000,0.000000,70.000000,21.000000,0.000000,18.000000,3.000000
50%,185.000000,0.500000,0.000000,5.000000,125.000000,34.000000,0.000000,32.000000,6.000000
75%,260.000000,2.000000,0.100000,10.000000,170.000000,50.750000,1.000000,43.750000,10.000000
max,510.000000,9.000000,0.300000,40.000000,340.000000,90.000000,8.000000,84.000000,20.000000

In [40]:
df['Beverage'].value_counts()

Tazo® Full-Leaf Red Tea Latte (Vanilla Rooibos)        12
Caffè Latte                                            12
Caffè Mocha (Without Whipped Cream)                    12
Caramel Macchiato                                      12
Cappuccino                                             12
Tazo® Full-Leaf Tea Latte                              12
White Chocolate Mocha (Without Whipped Cream)          12
Tazo® Chai Tea Latte                                   12
Hot Chocolate (Without Whipped Cream)                  12
Vanilla Latte (Or Other Flavoured Latte)               12
Tazo® Green Tea Latte                                  12
Coffee                                                 12
Strawberries & Crème (Without Whipped Cream)            9
Java Chip (Without Whipped Cream)                       9
Iced Brewed Coffee (With Milk & Classic Syrup)          9
Mocha (Without Whipped Cream)                           9
Caramel (Without Whipped Cream)                         9
Tazo® Tea                                               4
Caffè Americano                                         4
Brewed Coffee                                           4
Skinny Latte (Any Flavour)                              4
Caramel Apple Spice (Without Whipped Cream)             4
Vanilla Bean (Without Whipped Cream)                    4
Banana Chocolate Smoothie                               3
Shaken Iced Tazo® Tea Lemonade (With Classic Syrup)     3
Java Chip                                               3
Caramel                                                 3
Orange Mango Banana Smoothie                            3
Shaken Iced Tazo® Tea (With Classic Syrup)              3
Strawberry Banana Smoothie                              3
Mocha                                                   3
Iced Brewed Coffee (With Classic Syrup)                 3
Espresso                                                2
Name: Beverage, dtype: int64

In [41]:
df['Beverage_category'].value_counts()

Classic Espresso Drinks              58
Tazo® Tea Drinks                     52
Signature Espresso Drinks            40
Frappuccino® Blended Coffee          36
Shaken Iced Beverages                18
Frappuccino® Blended Crème           13
Frappuccino® Light Blended Coffee    12
Smoothies                             9
Coffee                                4
Name: Beverage_category, dtype: int64